[package]
name = "fast_cocluster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
rayon = "1.5.1"
ndarray-parallel = "0.9.1"
nalgebra = "0.26.2"
kmeans = { path = "kmean-rs" }
rand = "0.8.5"
ndarray-rand = "0.14.0"
